# Generated by Django 4.0.4 on 2022-04-14 15:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import serd.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('state', models.CharField(choices=[('aktive', 'Aktiv'), ('open', 'offen'), ('full', 'Keine Kapaizitäten')], max_length=64, verbose_name='Status')),
                ('food', models.CharField(blank=True, choices=[('breakfast', 'Frühstück'), ('inclusive', 'Inklusive'), ('space-eye', 'Durch Space-Eye')], max_length=64, verbose_name='Verpflegung')),
                ('cost', models.CharField(max_length=128, verbose_name='Kosten')),
                ('beds_adults', models.PositiveSmallIntegerField(validators=[serd.validators.validate_not_negative], verbose_name='Betten Erwachsene')),
                ('beds_children', models.PositiveSmallIntegerField(validators=[serd.validators.validate_not_negative], verbose_name='Betten Kinder')),
                ('adults_free', models.IntegerField(blank=True, null=True, verbose_name='NICHTS EINTRAGEN, TECHNISCHES FELD, KOMMT BALD WEG')),
                ('children_free', models.IntegerField(blank=True, null=True, verbose_name='NICHTS EINTRAGEN, TECHNISCHES FELD, KOMMT BALD WEG')),
                ('info', models.TextField(blank=True, verbose_name='Info')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_hotel', to=settings.AUTH_USER_MODEL, verbose_name='Zuständig Meldung')),
                ('team_gesamt', models.ManyToManyField(related_name='tem_for_hotel', to=settings.AUTH_USER_MODEL, verbose_name='Team gesamt')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=128, verbose_name='Nachname')),
                ('given_name', models.CharField(max_length=128, verbose_name='Vorname')),
                ('plz', models.CharField(max_length=5, validators=[serd.validators.validate_plz], verbose_name='Postleitzahl')),
                ('total_number', models.PositiveSmallIntegerField(default=1, validators=[serd.validators.validate_not_negative], verbose_name='Gesamtanzahl der Personen')),
                ('children_number', models.PositiveSmallIntegerField(null=True, validators=[serd.validators.validate_not_negative], verbose_name='davon Kinder unter zwölf')),
                ('street', models.CharField(blank=True, max_length=256, verbose_name='Straße (optional')),
                ('city', models.CharField(max_length=256, verbose_name='Ort')),
                ('phone', models.CharField(max_length=50, validators=[serd.validators.validate_phone], verbose_name='Telephonnummer')),
                ('mail', models.CharField(max_length=256, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail Adresse')),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11, verbose_name='Gesprochene Sprachen')),
                ('for_free', models.BooleanField(verbose_name='kostenfreie Unterkunft')),
                ('cost', models.PositiveSmallIntegerField(null=True, validators=[serd.validators.validate_not_negative], verbose_name='Monatsmiete')),
                ('spontan', models.BooleanField(verbose_name='Spontan Verfügbar')),
                ('available_from', models.DateField(verbose_name='Verfügbar Ab')),
                ('limited_availability', models.BooleanField(verbose_name='Nur vorrübergehend Verfügbar')),
                ('available_until', models.DateField(verbose_name='Verfügbar bis')),
                ('accessability', models.BooleanField(verbose_name='Barrierefrei')),
                ('public_transport', models.BooleanField(verbose_name='Mit ÖPNV Erreichbar')),
                ('rooms', models.SmallIntegerField(verbose_name='Anzahl Zimmer')),
                ('seperate_appartment', models.BooleanField(verbose_name='Unterkunft ist eine eigenständige Wohnung')),
                ('living_with', models.CharField(blank=True, choices=[('single', 'alleine'), ('family', 'mit Familie'), ('friends', 'mit Freunden')], max_length=64, verbose_name='Meine Wohnsituation')),
                ('pets', multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Hund'), ('cat', 'Katze'), ('small', 'Kleintier'), ('none', 'Keine')], max_length=18, verbose_name='Haustiere Erlaubt')),
                ('state', models.CharField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('request_contact', 'Kontakt zu Gast'), ('arrived', 'Gast ist Angekommen'), ('stale', 'Nicht mehr verfügbar'), ('free', 'Unterkunft wieder Verfügbar'), ('reserved', 'Reserviert')], default='new', max_length=64, verbose_name='Status')),
                ('comment', models.CharField(blank=True, max_length=512, verbose_name='Kommentar')),
                ('private_comment', models.CharField(blank=True, default='', max_length=512, verbose_name='Interner Kommentar')),
                ('by_municipality', models.BooleanField(default=False, verbose_name='Von Stadt Vermittelt')),
            ],
        ),
        migrations.CreateModel(
            name='HousingRequest',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=128, verbose_name='Nachname')),
                ('given_name', models.CharField(max_length=128, verbose_name='Vorname')),
                ('name_slug', models.CharField(blank=True, default='', max_length=256)),
                ('phone', models.CharField(max_length=50, validators=[serd.validators.validate_phone], verbose_name='Telephonnummer')),
                ('mail', models.CharField(max_length=256, validators=[django.core.validators.EmailValidator()], verbose_name='E-Mail Adresse')),
                ('representative', models.CharField(blank='true', max_length=256)),
                ('repr_phone', models.CharField(blank='true', max_length=256, validators=[serd.validators.validate_phone])),
                ('repr_mail', models.CharField(max_length=256, validators=[django.core.validators.EmailValidator()])),
                ('adults', models.PositiveSmallIntegerField(validators=[serd.validators.validate_not_negative], verbose_name='Anzahl Erwachsener')),
                ('children', models.PositiveSmallIntegerField(validators=[serd.validators.validate_not_negative], verbose_name='Anzahl Kinder')),
                ('who', models.CharField(max_length=256, verbose_name='Kurze Beschreibung')),
                ('split', models.BooleanField(verbose_name='Gruppe darf geteilt werden')),
                ('current_housing', models.CharField(choices=[('none', 'Ich habe keinen Schlafplatz'), ('friends', 'Bei Freunden oder Verwandten'), ('shelter', 'Staatliche Notunterkunft'), ('hotel', 'Im Hotel')], max_length=128, verbose_name='Aktuelle Unterbringung')),
                ('arrival_date', models.DateField(verbose_name='Ankunftstag')),
                ('arrival_location', models.CharField(max_length=256, verbose_name='Ankunftsort')),
                ('pets', multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Hund'), ('cat', 'Katze'), ('small', 'Kleintier'), ('none', 'Keine')], max_length=18, verbose_name='Haustiere')),
                ('pet_number', models.PositiveSmallIntegerField(null=True, validators=[serd.validators.validate_not_negative], verbose_name='Anzahl der Haustiere')),
                ('car', models.BooleanField(verbose_name='Auto verfügbar')),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11, verbose_name='Gesprochene Sprachen')),
                ('vaccination', models.BooleanField(verbose_name='Alle Personen vollständig geimpft')),
                ('accessability_needs', models.BooleanField(verbose_name='Barrierefreie Wohnung benötigt')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Erhöht'), ('high', 'Hoch')], max_length=64, verbose_name='Priorität')),
                ('state', models.CharField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('stale', 'nicht mehr aktuell'), ('housing_contact', 'Kontakt mit Unterkunft'), ('arrived', 'In Unterkunft angekommen')], default='new', max_length=64, verbose_name='Status')),
                ('private_comment', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Interner Kommentar')),
                ('case_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sachbearbeiter:in')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='serd.hotel', verbose_name='Hotel')),
                ('placed_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serd.offer', verbose_name='Vermitttelt an')),
            ],
        ),
        migrations.CreateModel(
            name='AnsprechpartnerHotel',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('tel', models.CharField(blank=True, max_length=128, validators=[serd.validators.validate_phone], verbose_name='Telefonnummer')),
                ('mail', models.CharField(blank=True, max_length=128, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ansprechpartner', to='serd.hotel')),
            ],
        ),
    ]
