# Generated by Django 2.2.24 on 2022-03-31 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement_Request',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=128)),
                ('given_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=256)),
                ('representative', models.CharField(max_length=256)),
                ('repr_phone', models.CharField(max_length=256)),
                ('repr_mail', models.CharField(max_length=256)),
                ('adults', models.PositiveSmallIntegerField()),
                ('children', models.PositiveSmallIntegerField()),
                ('share_permission', models.CharField(max_length=256)),
                ('current_housing', models.TextField()),
                ('arrival_date', models.DateTimeField()),
                ('arrival_location', models.TextField()),
                ('pets', models.CharField(max_length=128)),
                ('pet_number', models.PositiveSmallIntegerField()),
                ('car', models.BooleanField()),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11)),
                ('vaccination', models.BooleanField()),
                ('accessability_needs', models.BooleanField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Erhöht'), ('high', 'Hoch')], max_length=64)),
                ('case_handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=128)),
                ('given_name', models.CharField(max_length=128)),
                ('plz', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=256)),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11)),
                ('cost', models.PositiveSmallIntegerField()),
                ('spontan', models.BooleanField()),
                ('available_from', models.DateField()),
                ('limited_availabiltiy', models.BooleanField()),
                ('available_until', models.DateField()),
                ('accesability', models.BooleanField()),
                ('public_transport', models.BooleanField()),
                ('rooms', models.SmallIntegerField()),
                ('seperate_appartment', models.BooleanField()),
                ('civil_status', models.CharField(choices=[('single', 'ledig'), ('married', 'verheiratet')], max_length=64)),
                ('pets', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('closed', 'Vermittelt')], max_length=64)),
                ('placed_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serd.Placement_Request')),
            ],
        ),
    ]
