# Generated by Django 2.2.24 on 2022-03-31 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='placed_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serd.Placement_Request'),
        ),
    ]
