# Generated by Django 4.0.4 on 2022-04-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingrequest',
            name='possible_hosts',
            field=models.ManyToManyField(blank=True, related_name='possible_guests', to='serd.offer', verbose_name='Mögliche Gastgeber'),
        ),
    ]
