# Generated by Django 4.0.4 on 2022-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0002_housingrequest_possible_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingrequest',
            name='arrival_location',
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='priority',
            field=models.CharField(blank=True, choices=[('1normal', 'Normal'), ('2elevated', 'Erhöht'), ('3high', 'Hoch')], max_length=64, verbose_name='Priorität'),
        ),
    ]
