# Generated by Django 2.2.24 on 2022-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0002_auto_20220331_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement_request',
            name='arrival_location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='placement_request',
            name='current_housing',
            field=models.CharField(max_length=256),
        ),
    ]
