# Generated by Django 4.0.4 on 2022-04-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0003_remove_housingrequest_arrival_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingrequest',
            name='private_comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='who',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
