# Generated by Django 2.2.24 on 2022-03-31 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0003_auto_20220331_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement_request',
            name='case_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
