# Generated by Django 2.2.24 on 2022-03-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0004_auto_20220331_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placement_request',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
