# Generated by Django 4.0.4 on 2022-04-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0004_alter_housingrequest_private_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('headline', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
    ]
