# Generated by Django 4.0.4 on 2022-04-25 18:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import serd.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serd', '0005_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('mail', models.CharField(blank=True, max_length=256, validators=[django.core.validators.EmailValidator()], verbose_name='E-Mail-Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, validators=[serd.validators.validate_phone], verbose_name='Telefonnummer')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='Telegram')),
                ('threema', models.CharField(max_length=64, verbose_name='Threema')),
                ('whatsapp', models.BooleanField(verbose_name='Whatsapp')),
                ('signal', models.BooleanField(verbose_name='Signal')),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11, null=True, verbose_name='Sprachkenntnisse')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
        ),
    ]
