# Generated by Django 2.2.24 on 2022-03-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0005_auto_20220331_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='accesability',
            new_name='accessability',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='limited_availabiltiy',
            new_name='limited_availability',
        ),
    ]
