# Generated by Django 4.0.4 on 2022-04-25 19:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11, null=True, verbose_name='Sprachkenntnisse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='threema',
            field=models.CharField(blank=True, max_length=64, verbose_name='Threema'),
        ),
    ]
