# Generated by Django 2.2.24 on 2022-04-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0006_auto_20220331_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement_request',
            old_name='share_permission',
            new_name='who',
        ),
        migrations.AddField(
            model_name='placement_request',
            name='split',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
