# Generated by Django 4.0.4 on 2022-04-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0007_alter_profile_languages_alter_profile_threema'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.CharField(blank=True, max_length=128, verbose_name='Kommentar'),
        ),
    ]
