# Generated by Django 2.2.24 on 2022-04-01 16:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0007_auto_20220401_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='civil_status',
            field=models.CharField(choices=[('single', 'alleine'), ('family', 'mit Familie'), ('friends', 'mit Freunden')], max_length=64),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pets',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='placement_request',
            name='current_housing',
            field=models.CharField(choices=[('none', 'Ich habe keinen Schlafplatz'), ('friends', 'Bei Freunden oder Verwandten'), ('hotel', 'Hotel')], max_length=128),
        ),
        migrations.AlterField(
            model_name='placement_request',
            name='pets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Hund'), ('cat', 'Katze'), ('small', 'Kleintier')], max_length=13),
        ),
    ]
