# Generated by Django 2.2.24 on 2022-04-01 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0009_auto_20220401_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='civil_status',
            new_name='living_with',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='placed_request',
        ),
        migrations.AddField(
            model_name='offer',
            name='city',
            field=models.CharField(default='Regensburg', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='private_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='street',
            field=models.CharField(default='StreetStreet', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placement_request',
            name='placed_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serd.Offer'),
        ),
    ]
