# Generated by Django 4.0.4 on 2022-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0009_alter_offer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingrequest',
            name='room',
            field=models.CharField(blank=True, max_length=64, verbose_name='Zimmernummer'),
        ),
    ]
