# Generated by Django 4.0.4 on 2022-04-26 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0009_alter_offer_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelStay',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_date', models.DateField(verbose_name='Ankunftstag')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Abreisetag')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='serd.hotel')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='serd.housingrequest')),
            ],
        ),
    ]
