# Generated by Django 4.0.4 on 2022-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0010_housingrequest_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansprechpartnerhotel',
            name='hotel',
        ),
        migrations.AddField(
            model_name='ansprechpartnerhotel',
            name='hotel',
            field=models.ManyToManyField(null=True, related_name='ansprechpartner', to='serd.hotel'),
        ),
    ]
