# Generated by Django 2.2.24 on 2022-04-02 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serd', '0010_auto_20220401_2154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Placement_Request',
            new_name='HousingRequest',
        ),
    ]
