# Generated by Django 2.2.24 on 2022-04-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0011_auto_20220402_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingrequest',
            name='state',
            field=models.TextField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('stale', 'nicht mehr aktuell'), ('housing_contact', 'Kontakt mit Unterkunft'), ('arrived', 'In Unterkunft angekommen')], default='contacted'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='arrival_date',
            field=models.DateField(),
        ),
    ]
