# Generated by Django 4.0.4 on 2022-04-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0010_hotelstay'),
        ('serd', '0012_alter_hotel_state'),
    ]

    operations = [
    ]
