# Generated by Django 2.2.24 on 2022-04-02 14:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0012_auto_20220402_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingrequest',
            name='private_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='pets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Hund'), ('cat', 'Katze'), ('small', 'Kleintier'), ('none', 'Keine')], max_length=18),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Hund'), ('cat', 'Katze'), ('small', 'Kleintier'), ('none', 'Keine')], max_length=18),
        ),
        migrations.AlterField(
            model_name='offer',
            name='state',
            field=models.CharField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('request_contact', 'Kontakt zu Gast'), ('arrived', 'Gast ist Angekommen'), ('stale', 'Nicht mehr verfügbar'), ('free', 'Unterkunft wieder Verfügbar'), ('reserved', 'Reserviert')], max_length=64),
        ),
    ]
