# Generated by Django 2.2.24 on 2022-04-07 19:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import serd.validators


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0013_auto_20220402_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingrequest',
            name='accessability_needs',
            field=models.BooleanField(verbose_name='Barrierefreie Wohnung benötigt'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='adults',
            field=models.PositiveSmallIntegerField(verbose_name='Anzahl Erwachsener'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='arrival_date',
            field=models.DateField(verbose_name='Ankunftstag'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='arrival_location',
            field=models.CharField(max_length=256, verbose_name='Ankunftsort'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='car',
            field=models.BooleanField(verbose_name='Auto verfügbar'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='case_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sachbearbeiter:in'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='children',
            field=models.PositiveSmallIntegerField(verbose_name='Anzahl Kinder'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='current_housing',
            field=models.CharField(choices=[('none', 'Ich habe keinen Schlafplatz'), ('friends', 'Bei Freunden oder Verwandten'), ('hotel', 'Hotel')], max_length=128, verbose_name='Aktuelle Unterbringung'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='given_name',
            field=models.CharField(max_length=128, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11, verbose_name='Gesprochene Sprachen'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='mail',
            field=models.CharField(max_length=256, validators=[django.core.validators.EmailValidator()], verbose_name='E-Mail Adresse'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='pet_number',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Anzahl der Haustiere'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='pets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Hund'), ('cat', 'Katze'), ('small', 'Kleintier'), ('none', 'Keine')], max_length=18, verbose_name='Haustiere'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='phone',
            field=models.CharField(max_length=50, validators=[serd.validators.validate_phone], verbose_name='Telephonnummer'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='placed_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serd.Offer', verbose_name='Vermitttelt an'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Erhöht'), ('high', 'Hoch')], max_length=64, verbose_name='Priorität'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='private_comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Interner Kommentar'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='split',
            field=models.BooleanField(verbose_name='Gruppe darf geteilt werden'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='state',
            field=models.TextField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('stale', 'nicht mehr aktuell'), ('housing_contact', 'Kontakt mit Unterkunft'), ('arrived', 'In Unterkunft angekommen')], default='new', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='vaccination',
            field=models.BooleanField(verbose_name='Alle Personen vollständig geimpft'),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='who',
            field=models.CharField(max_length=256, verbose_name='Kurze Beschreibung'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='accessability',
            field=models.BooleanField(verbose_name='Barrierefrei'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='available_from',
            field=models.DateField(verbose_name='Verfügbar Ab'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='available_until',
            field=models.DateField(verbose_name='Verfügbar bis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='city',
            field=models.CharField(max_length=256, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='cost',
            field=models.PositiveSmallIntegerField(verbose_name='Monatsmiete'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='given_name',
            field=models.CharField(max_length=128, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11, verbose_name='Gesprochene Sprachen'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='limited_availability',
            field=models.BooleanField(verbose_name='Nur vorrübergehend Verfügbar'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='living_with',
            field=models.CharField(choices=[('single', 'alleine'), ('family', 'mit Familie'), ('friends', 'mit Freunden')], max_length=64, verbose_name='Meine Wohnsituation'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='mail',
            field=models.CharField(max_length=256, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail Adresse'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Hund'), ('cat', 'Katze'), ('small', 'Kleintier'), ('none', 'Keine')], max_length=18, verbose_name='Haustiere Erlaubt'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='phone',
            field=models.CharField(max_length=50, validators=[serd.validators.validate_phone], verbose_name='Telephonnummer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='plz',
            field=models.CharField(max_length=5, validators=[serd.validators.validate_plz], verbose_name='Postleitzahl'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='private_comment',
            field=models.TextField(blank=True, default='', verbose_name='Interner Kommentar'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='public_transport',
            field=models.BooleanField(verbose_name='Mit ÖPNV Erreichbar'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='rooms',
            field=models.SmallIntegerField(verbose_name='Anzahl Zimmer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='seperate_appartment',
            field=models.BooleanField(verbose_name='Unterkunft ist eine eigenständige Wohnung'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='spontan',
            field=models.BooleanField(verbose_name='Spontan Verfügbar'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='state',
            field=models.CharField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('request_contact', 'Kontakt zu Gast'), ('arrived', 'Gast ist Angekommen'), ('stale', 'Nicht mehr verfügbar'), ('free', 'Unterkunft wieder Verfügbar'), ('reserved', 'Reserviert')], default='new', max_length=64, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='street',
            field=models.CharField(blank=True, max_length=256, verbose_name='Straße (optional'),
        ),
    ]
