# Generated by Django 4.0.4 on 2022-04-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0013_merge_0010_hotelstay_0012_alter_hotel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansprechpartnerhotel',
            name='hotel',
            field=models.ManyToManyField(related_name='ansprechpartner', to='serd.hotel'),
        ),
    ]
