# Generated by Django 4.0.4 on 2022-04-29 11:19

from django.db import migrations, models
import serd.validators


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0014_alter_ansprechpartnerhotel_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='adults_free',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='beds_adults',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='beds_children',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='children_free',
        ),
        migrations.RemoveField(
            model_name='housingrequest',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='housingrequest',
            name='room',
        ),
        migrations.AddField(
            model_name='hotel',
            name='beds',
            field=models.PositiveSmallIntegerField(default=1, validators=[serd.validators.validate_not_negative], verbose_name='Betten'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelstay',
            name='room',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
