# Generated by Django 2.2.24 on 2022-04-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0014_auto_20220407_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingrequest',
            name='name_slug',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
