# Generated by Django 4.0.4 on 2022-05-03 23:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0015_remove_hotel_adults_free_remove_hotel_beds_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], default=['de'], max_length=11, verbose_name='Welche Sprachen sprechen Sie?'),
        ),
    ]
