# Generated by Django 2.2.24 on 2022-04-09 12:06

import django.core.validators
from django.db import migrations, models
import serd.validators


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0015_housingrequest_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingrequest',
            name='repr_mail',
            field=models.CharField(max_length=256, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='repr_phone',
            field=models.CharField(blank='true', max_length=256, validators=[serd.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='representative',
            field=models.CharField(blank='true', max_length=256),
        ),
    ]
