# Generated by Django 4.0.4 on 2022-05-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0016_alter_offer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingrequest',
            name='smoker',
            field=models.BooleanField(default=False, verbose_name='Raucht jemand aus Ihrer Gruppe?'),
            preserve_default=False,
        ),
    ]
