# Generated by Django 4.0.4 on 2022-05-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0017_housingrequest_smoker'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Sichtbar'),
        ),
    ]
