# Generated by Django 4.0.4 on 2022-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0018_hotel_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
