# Generated by Django 3.2.12 on 2022-05-23 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serd', '0020_alter_housingrequest_languages_alter_offer_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Personen von')),
                ('num_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Personen bis')),
                ('PLZ', models.CharField(blank=True, max_length=5, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Ort')),
                ('cost_min', models.PositiveSmallIntegerField(blank=b'I01\n', null=True, verbose_name='Kosten von')),
                ('cost_max', models.PositiveSmallIntegerField(blank=b'I01\n', null=True, verbose_name='Kosten bis')),
                ('language', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11, verbose_name='Sprachen')),
                ('spontan', models.BooleanField(null=True, verbose_name='Spontan')),
                ('limited', models.BooleanField(null=True, verbose_name='Begrenzt verfügbar')),
                ('appartment', models.BooleanField(null=True, verbose_name='Eigene Wohnung')),
                ('pets', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dog', 'Hund'), ('cat', 'Katze'), ('small', 'Kleintier'), ('none', 'Keine')], max_length=18, null=True, verbose_name='Haustiere')),
                ('accessability', models.BooleanField(null=True, verbose_name='Barrierefrei')),
                ('state', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('request_contact', 'Kontakt zu Gast'), ('arrived', 'Gast ist Angekommen'), ('stale', 'Nicht mehr verfügbar'), ('free', 'Unterkunft wieder Verfügbar'), ('reserved', 'Reserviert'), ('no', 'Nicht Tragbar')], max_length=60, null=True, verbose_name='Status')),
                ('for_free', models.BooleanField(null=True, verbose_name='Gratis')),
                ('sort', models.CharField(choices=[('number', 'Nummer'), ('last_name', 'Nachname'), ('plz', 'PLZ'), ('cost', 'Kosten')], default='number', max_length=64, verbose_name='Sortierung')),
                ('sort_direction', models.CharField(choices=[('asc', 'Aufsteigend'), ('desc', 'Absteigend')], default='asc', max_length=64, verbose_name='Auf/Absteigend')),
            ],
        ),
        migrations.CreateModel(
            name='RequestFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Personen von')),
                ('num_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Personen bis')),
                ('split', models.BooleanField(null=True, verbose_name='Teilbar')),
                ('current_housing', models.BooleanField(null=True, verbose_name='Aktuelle Unterbringung')),
                ('pets', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dog', 'Hund'), ('cat', 'Katze'), ('small', 'Kleintier'), ('none', 'Keine')], max_length=18, null=True, verbose_name='Haustiere')),
                ('languages', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11, null=True, verbose_name='Sprachen')),
                ('accessability_needs', models.BooleanField(null=True, verbose_name='Barrierefrei')),
                ('priority', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1normal', 'Normal'), ('2elevated', 'Erhöht'), ('3high', 'Hoch')], max_length=23, null=True, verbose_name='Priorität')),
                ('state', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('stale', 'nicht mehr aktuell'), ('housing_contact', 'Kontakt mit Unterkunft'), ('arrived', 'In Unterkunft angekommen'), ('no', 'Nicht vermittelbar')], max_length=46, null=True, verbose_name='Status')),
                ('no_handler', models.BooleanField(null=True, verbose_name='Kein Sachbearbeiter')),
                ('sort', models.CharField(choices=[('number', 'Nummer'), ('last_name', 'Nachname'), ('priority', 'Priorität')], default='number', max_length=64, verbose_name='Sortierung')),
                ('sort_direction', models.CharField(choices=[('asc', 'Aufsteigend'), ('desc', 'Absteigend')], default='asc', max_length=64, verbose_name='Auf/Absteigend')),
                ('case_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_filter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serd.offerfilter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='request_filter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serd.requestfilter'),
        ),
    ]
