# Generated by Django 3.2.12 on 2022-05-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0021_auto_20220523_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingrequest',
            name='profession',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Welchen Beruf üben Sie aus?'),
        ),
        migrations.AlterField(
            model_name='offerfilter',
            name='cost_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kosten bis'),
        ),
        migrations.AlterField(
            model_name='offerfilter',
            name='cost_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kosten von'),
        ),
    ]
