# Generated by Django 3.2.12 on 2022-06-28 17:23

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import serd.validators


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0023_auto_20220606_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pate',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=128, validators=[serd.validators.validate_not_empty], verbose_name='Nachname')),
                ('given_name', models.CharField(blank=True, max_length=128, verbose_name='Vorname')),
                ('city', models.CharField(blank=True, max_length=256, verbose_name='Wohnort')),
                ('district', models.CharField(blank=True, max_length=128, verbose_name='Stadtteil')),
                ('languages', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('de', 'Deutsch'), ('uk', 'Ukrainisch'), ('ru', 'Russisch'), ('en', 'Englisch')], max_length=11, null=True, verbose_name='Sprachkenntnisse')),
                ('additional_languages', models.CharField(blank=True, max_length=64, verbose_name='Weitere Sprachen')),
                ('phone', models.CharField(blank=True, max_length=50, validators=[serd.validators.validate_phone], verbose_name='Telefonnummer')),
                ('mail', models.CharField(blank=True, max_length=256, validators=[django.core.validators.EmailValidator()], verbose_name='E-Mail-Adresse')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
            ],
        ),
    ]
