# Generated by Django 3.2.12 on 2022-07-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serd', '0024_pate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pate',
            name='state',
            field=models.CharField(choices=[('new', 'neu'), ('contacted', 'kontaktiert'), ('placed', 'vermittelt')], default='new', max_length=64),
        ),
    ]
